<?php
/**
 * @package     Plumrocket_SocialLoginFree
 * @copyright   Copyright (c) 2018 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license   End-user License Agreement
 */
?>

<?php
/** @var \Plumrocket\SocialLoginFree\Helper\Data $helper */
$helper = $this->helper('Plumrocket\SocialLoginFree\Helper\Data');
if ($helper->moduleEnabled()): ?>
    <?php if ($helper->isFakeMail()): ?>
        <script type="text/javascript">
        //<![CDATA[
            require([
                'jquery',
                'domReady!'
            ], function($) {
                'use strict';

                $('div.password.current').hide();

                $('#change-email, #change-password').each(function (){
                    var el = $(this);
                    el.parent('.field').hide();
                    el.prop('checked', true).on('click', function (){
                        return false;
                    });
                });
            });
        //]]>
        </script>
    <?php endif; ?>
<?php endif; ?>
