<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block Plumrocket\Amp\Block\Catalog\LayeredNavigation\RenderLayered */
?>
<?php $swatchData = $block->getSwatchData(); ?>
<div id="swatch-filter-<?php /* @escapeNotVerified */ echo $swatchData['attribute_code'] ?>" hidden class="swatch-attribute swatch-layered <?php /* @escapeNotVerified */ echo $swatchData['attribute_code'] ?>">
    <ul class="swatch-attribute-options clearfix">
        <?php foreach ($swatchData['options'] as $option => $label): ?>
            <li>
                <a href="<?php /* @escapeNotVerified */ echo $label['link'] ?>" class="swatch-option-link-layered">
                    <?php if (isset($swatchData['swatches'][$option]['type'])) { ?>
                        <?php switch ($swatchData['swatches'][$option]['type']) {
                            case '3':
                                ?>
                                <div class="swatch-option <?php /* @escapeNotVerified */ echo $label['custom_style'] ?>"
                                     data-option-type="3"
                                     data-option-id="<?php /* @escapeNotVerified */ echo $option ?>"
                                     data-option-label="<?php /* @escapeNotVerified */ echo $label['label'] ?>"
                                    ><?php /* @escapeNotVerified */ echo $label['label'] ?></div>
                                <?php    break;
                            case '2':
                                ?>
                                <?php $swatchThumbPath = $block->getSwatchPath('swatch_thumb',
                                $swatchData['swatches'][$option]['value']); ?>
                                <?php $swatchImagePath = $block->getSwatchPath('swatch_image',
                                $swatchData['swatches'][$option]['value']); ?>
                                <div class="swatch-option image <?php /* @escapeNotVerified */ echo $label['custom_style'] ?>"
                                     data-option-type="2"
                                     data-option-id="<?php /* @escapeNotVerified */ echo $option ?>"
                                     data-option-label="<?php /* @escapeNotVerified */ echo $label['label'] ?>"
                                     data-option-tooltip-thumb="<?php /* @escapeNotVerified */ echo $swatchThumbPath ?>"
                                     data-option-tooltip-value=""
                                >
                                    <?php if(!$swatchImagePath) : ?>
                                        <?php /* @escapeNotVerified */ echo $label['label'] ?>
                                    <?php else : ?>
                                        <amp-img fallback width="40" height="40" src="<?php /* @escapeNotVerified */ echo $swatchImagePath ?>"></amp-img>
                                    <?php endif; ?>
                                </div>
                                <?php    break;
                            case '1':
                                ?>
                                <table class="swatch-option color <?php /* @escapeNotVerified */ echo $label['custom_style'] ?>"
                                     data-option-type="1"
                                     data-option-id="<?php /* @escapeNotVerified */ echo $option ?>"
                                     data-option-label="<?php /* @escapeNotVerified */ echo $label['label'] ?>"
                                     data-option-tooltip-thumb=""
                                     data-option-tooltip-value="<?php /* @escapeNotVerified */ echo $swatchData['swatches'][$option]['value'] ?>"
                                    >
                                    <tr><td bgcolor="<?php /* @escapeNotVerified */ echo $swatchData['swatches'][$option]['value'] ?>"></td></tr>
                                </table>
                                <?php    break;
                            case '0':
                            default:
                                ?>
                                    <div class="swatch-option text <?php /* @escapeNotVerified */ echo $label['custom_style'] ?>"
                                         data-option-type="0"
                                         data-option-id="<?php /* @escapeNotVerified */ echo $option ?>"
                                         data-option-label="<?php /* @escapeNotVerified */ echo $label['label'] ?>"
                                         data-option-tooltip-thumb=""
                                         data-option-tooltip-value=""
                                        ><?php /* @escapeNotVerified */ echo $swatchData['swatches'][$option]['value'] ?></div>
                                <?php    break;
                        } ?>
                    <?php } ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>