<?php
/**
 * @package     Plumrocket_SocialLoginFree
 * @copyright   Copyright (c) 2015 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license   End-user License Agreement
 */
?>
<?php /** @var \Plumrocket\SocialLoginFree\Block\Buttons $block */ ?>
<?php if ($block->hasButtons()) : ?>
    <div class="pslogin-block pslogin-register" data-mage-init='{"pslogin":{}}'>

        <div class="pslogin-buttons <?= $block->showShortButtons() ? '' : 'pslogin-buttons-showfull' ?>">

            <?php if ($block->showShortButtons()) : ?>
                <div class="pslogin-spacer"><?= __('Register with your social account') ?></div>
                <br />
            <?php endif; ?>

            <ul>
            <?php foreach ($block->getPreparedButtons() as $button) : ?>
                <li class="pslogin-button <?= $block->escapeHtmlAttr($button['type']) ?>"
                    title="<?= $block->escapeHtmlAttr($button['register_text']) ?>">
                    <a class="pslogin-button-link pslogin-button-click"
                       rel="nofollow"
                       href="javascript:void(0);"
                       data-href="<?= $block->escapeHtmlAttr($button['href']) ?>"
                       data-width="<?= $block->escapeHtmlAttr($button['popup_width']) ?>"
                       data-height="<?= $block->escapeHtmlAttr($button['popup_height']) ?>" >

                        <?php if (! $block->showShortButtons()) : ?>
                            <?php if (! empty($button['image']['register'])) : ?>
                                <img class="pslogin-button-image"
                                     src="<?= $block->escapeUrl($button['image']['register']) ?>" />
                            <?php else : ?>
                                <span class="pslogin-button-auto">
                                    <span class="pslogin-button-icon">
                                        <?php if (! empty($button['image']['icon'])) : ?>
                                            <img class="pslogin-button-icon-image" src="<?= $block->escapeUrl($button['image']['icon']) ?>" />
                                        <?php endif; ?>
                                    </span>
                                    <span class="pslogin-button-text"><?= $block->escapeHtml($button['register_text']) ?></span>
                                </span>
                            <?php endif; ?>
                        <?php else : ?>
                            <?php if (! empty($button['image']['icon'])) : ?>
                                <img class="pslogin-button-icon-image"
                                     src="<?= $block->escapeUrl($button['image']['icon']) ?>"
                                     alt="<?= $block->escapeHtmlAttr(__('Icon of %1', $button['type'])) ?>"/>
                            <?php else : ?>
                                <span class="pslogin-button-auto">
                                    <span class="pslogin-button-icon"></span>
                                </span>
                            <?php endif; ?>
                        <?php endif; ?>
                    </a>
                </li>
            <?php endforeach; ?>
            </ul>
        </div>

    </div>
    <div style="clear: both;"></div>
<?php endif; ?>
