<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket Amp
 * @copyright   Copyright (c) 2018 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<?php
// @codingStandardsIgnoreFile

/** @var \Plumrocket\Amp\Block\Adminhtml\Widget\Notice $block */
?>

<?php if ($block->canShow()) : ?>
    <div class="amp-protocol-notice message"><?= __('According to AMP technology requirements, widget works only on the pages with https protocol') ?></div>
<?php endif; ?>
