<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_AjaxSocialLogin
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>

<?php
//  @codingStandardsIgnoreFile
?>
<tr id="general_sortsocial" <?php echo (!$buttons = $this->getButtons())? 'style="display: none;"' : ''; ?>>
    <td class="label"><?php echo $this->element->getLabel(); ?></td>
    <td colspan="3" class="social-td">        
        <div style="clear: both"></div>
        <div class="sociallogin-form">
            <ul id="sort-social" data-list="sort" class="sort-social">
            <?php foreach ($this->getPreparedButtons() as $button) : ?>
                <li id="sort-<?php echo $button['type']; ?>" class="<?php echo $button['type']; ?>">
                    <span class="social-icon"></span>
                    <span class="social-text"><?php echo $this->escapeHtml(ucfirst($button['type'])); ?></span>
                </li>
            <?php endforeach ?>
            </ul>
    </td>
</tr>