<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Amp v2.x.x
 * @copyright   Copyright (c) 2019 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */

/**
 * @var $block \Plumrocket\Amp\Block\Page\Facebook\Pixel
 */

$pageTitleBlock = $block->getLayout()->getBlock('page.main.title');
$pageTitle = $pageTitleBlock ? $pageTitleBlock->getPageTitle() : '';
?>

,"trackSearch": {
    "on": "visible",
    "request": "eventSearch",
    "vars": {
        "content_type": "product_group",
        "search_string": "<?= $block->escapeHtml($pageTitle)?>"
    }
}
