<script type="text/javascript">
    require([
        'jquery',
        'Magento_Ui/js/modal/confirm'
    ], function ($, confirm) {
        window.clearWebpImage = function() {
            confirm({
                title: '<?= __("Clear Image") ?>',
                content: '<?= __("Do you want to delete all generated webp images") ?>',
                actions: {
                    confirm: function(){ window.location.href = "<?= $block->getAdminUrl() ?>"},
                    cancel: function(){ return false },
                    always: function(){ return false }
                }
            });
        }
    });
</script>

<?php echo $block->getButtonHtml() ?>