<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block block-customer-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Registered Customers')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                <div class="field note"><?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?></div>
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input placeholder="<?= $block->escapeHtml(__('Email')) ?>" name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                        <div class="clslogin cls_user"></div>
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control cls_password">
                        <input placeholder="<?= $block->escapeHtml(__('Password')) ?>" name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                        <div class="clslogin cls_eye"></div>
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
					<div class="secondary cls_forget"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                    
				</div>
            </fieldset>
        </form>
    </div>
</div>
<div id="errorpopup-modal" style="display:none;" >   </div>

<script>
	require(
	[
	    'jquery',
	    'Magento_Ui/js/modal/modal'
	],
	function(
	    $,
	    modal
	){
$(window).load(function() {
	function show_loginerror_popup(){
		
		if ($(".lusererror")[0]){
			var options = {
                    type: 'popup',
					modalClass: 'country-popup-modal-wraper',
                    title: $.mage.__('<?php echo __("Account Does Not Exist"); ?>'),
                    responsive: true,
                    innerScroll: true
                 };
                $('#errorpopup-modal').html('');
                $('#errorpopup-modal').html(  $('.lusererror').html()   );
				
                var popup = modal(options, $('#errorpopup-modal'));			
			    $("#errorpopup-modal").modal("openModal");
				$('.page.messages').hide();
		}

			if ($(".lpasswroderror")[0]){
				var options = {
						type: 'popup',
						modalClass: 'country-popup-modal-wraper',
						title: $.mage.__('<?php echo __("Incorrect Password"); ?>'),
						responsive: true,
						innerScroll: true
					 };
					$('#errorpopup-modal').html('');
					$('#errorpopup-modal').html(  $('.lpasswroderror').html()   );
					
					var popup = modal(options, $('#errorpopup-modal'));			
					$("#errorpopup-modal").modal("openModal");
					$('.page.messages').hide();
			}
	}
        window.setTimeout( show_loginerror_popup, 1500 );
		
		
		});    
	});    
	
</script>