<div class="clshome">
	<span><a href="<?php echo $block->getBaseUrl(); ?>" title="Home">Home</a></span>
</div>
<?php
	
    /*$product_view = $this->getConfig('porto_settings/category');
    $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
    if($block) {
        $block->setBlockId($product_view['side_custom_block']);
    }
    if($block){
        echo $block->toHtml();
    }*/
?>