<?php
/**
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

// @codingStandardsIgnoreFile

?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
<?php $_product = $block->getProduct(); ?>

<div class="product-add-form">
    <form action="<?= $block->getUrl('wishlist/index/add') ?>" method="post"
          id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" name="product" value="<?= $_product->getId() ?>"/>
        <input type="hidden" name="selected_configurable_option" value=""/>
        <input type="hidden" name="related_product" id="related-products-field" value=""/>
        <?= $block->getBlockHtml('formkey') ?>
        <?= $block->getChildHtml('form_top'); ?>
        <?php if (!$block->hasOptions()): ?>
            <?= $block->getChildChildHtml('options_container') ?>

        <?php else: ?>
            <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1'): ?>
                <?= $block->getChildChildHtml('options_container') ?>
            <?php endif; ?>
        <?php endif; ?>

        <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2'): ?>
            <?= $block->getChildChildHtml('options_container') ?>
        <?php endif; ?>
        <?= $block->getChildHtml('form_bottom'); ?>
    </form>
    <script>
        require([
            'jquery',
            'Magento_Catalog/js/price-box'
        ], function ($) {
            var priceBoxes = $('.mb-ajaxsuite-popup-wrapper[data-role=priceBox]');

            priceBoxes = priceBoxes.filter(function (index, elem) {
                return !$(elem).find('.price-from').length;
            });

            priceBoxes.priceBox({'priceConfig': <?php /* @escapeNotVerified */ echo $block->getJsonConfig() ?>});
        });
    </script>
</div>
