<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}

$helper = $this->helper('\Zealousweb\AppleLogin\Helper\Data');
?>
<?php if( $helper->isEnabled() && $helper->isShowLoginPopup() ) :?>
	<li class="authorization-link" data-label="<?= $block->escapeHtmlAttr(__('or')) ?>">
	    <a href="javascript:void(0);" class="login-popup">
	        <?= $block->escapeHtml($block->getLabel()) ?>
	    </a>
	</li>
<?php else :?>
	<li class="authorization-link" data-label="<?= $block->escapeHtmlAttr(__('or')) ?>">
	    <a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?>>
	        <?= $block->escapeHtml($block->getLabel()) ?>
	    </a>
	</li>
<?php endif;?>
