<?php 
$helper = $this->helper('\Zealousweb\AppleLogin\Helper\Data');
$buttonLabel = $helper->getButtonLabel();
$displayType = $helper->getDisplayType();
$defaultImage = $helper->getDefaultImage();
$buttonLayout = $helper->getButtonLayout();
?>
<?php if($helper->isEnabled()) :?>
    <div id="apple-popup-modal" style="display:none;">

        <div class="block block-customer-login">
            <div class="popup-logo">
                <img src="<?php echo $helper->getLogoUrl();?>" alt="<?php echo $helper->getLogoAlt();?>">
            </div>
            <div class="block-content" aria-labelledby="block-customer-login-heading">
                <form class="form form-login"
                      action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
                      method="post"
                      id="login-form"
                      data-mage-init='{"validation":{}}'>
                    <?= $block->getBlockHtml('formkey') ?>
                    <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                        <div class="field email required">
                            <div class="control">
                                <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}" placeholder="<?php echo __('Email Address');?>">
                            </div>
                        </div>
                        <div class="field password required">
                            <div class="control">
                                <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}" placeholder="<?php echo __('Password');?>">
                            </div>
                        </div>
                        <?= $block->getChildHtml('form_additional_info') ?>
                        <?= $block->getChildHtml('zealousweb.gdpr.checkbox') ?>
                        <div class="actions-toolbar">
                            <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                            <div class="secondary"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>

        <div class="block block-customer-login apple-signup <?php echo (!empty($buttonLayout)) ? 'apple-btn-'.$buttonLayout: 'apple-btn-right'?>">
            <div class="space-container <?php echo (!empty($buttonLayout)) ? 'apple-icon-'.$buttonLayout: 'apple-icon-left'?>">
                <span class="space-container-inner"><span><?= $block->escapeHtml(__('Or')) ?></span></span>
            </div>
            <a href="javascript:void(0)" id="signinwithapple" class="action create primary signinwithapple  <?php echo  (!empty($displayType) && $displayType == \Zealousweb\AppleLogin\Model\Config\Source\DisplayType::DISPLAY_TYPE_BUTTON) ? '': 'login-icon';?>">
                <?php if( !empty($displayType) && $displayType == \Zealousweb\AppleLogin\Model\Config\Source\DisplayType::DISPLAY_TYPE_BUTTON ) :?>
                    <span class="apple-icon">
                        <?php if( !empty($helper->getButtonImage()) ) :?>
                            <?php 
                                $buttonImage = 'apple/'.$helper->getButtonImage();
                                $resizeImage = $helper->getResizeImage($buttonImage, 22, 27);
                            ?>
                            <img src="<?php echo $resizeImage; ?>">
                        <?php else :?>
                            <img src="<?php echo $defaultImage;?>">
                        <?php endif;?>
                    </span>
                    <span class="apple-btn-text">
                        <?= $buttonLabel; ?>
                    </span>
                <?php else :?>
                    <div class="apple-icon-inner">
                        <?php if( !empty($helper->getAppleIcon()) ) :?>
                            <?php 
                                $appleIcon = 'apple/'.$helper->getAppleIcon();
                                $resizeIcon = $helper->getResizeImage($appleIcon, 90, 90);
                            ?>
                            <img src="<?php echo $resizeIcon; ?>">
                        <?php else :?>
                            <img src="<?php echo $defaultImage;?>">
                        <?php endif;?>
                    </div>
                <?php endif;?>
            </a>
        </div>

        <script>
            require(['jquery','jquery/ui'], function($){
                $('#signinwithapple').on('click', function() {
                    var isiPad = navigator.userAgent.match(/iPad/i) != null;
                    var isiPhone = navigator.userAgent.match(/iPhone/i) != null;
                    if (isiPad || isiPhone) {
                        window.open('<?php echo $block->getUrl('applelogin/apple/redirect');?>');   
                    }else{
                        window.open('<?php echo $helper->getAuthorizationUrl();?>','popup','width=600,height=600'); 
                    }
                    return false;
                });
           });
        </script>

        <div class="register-link-container">
            <span class="register-link-inner">
                <?php echo __('Don\'t have an account?');?>
                <a href="<?php echo $this->getUrl('customer/account/create');?>">
                    <i class="fa fa-user" aria-hidden="true"></i><?php echo __('Sign Up Now');?>
                </a>
            </span>
        </div>

    </div>

    <script>
        require(
            [
                'jquery',
                'Magento_Ui/js/modal/modal'
            ],
            function(
                $,
                modal
            ) {
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    //title: 'popup modal title',
                    modalClass: 'apple-login-popup',
                    buttons: []
                };

                var popup = modal(options, $('#apple-popup-modal'));
                $(".login-popup").on('click',function(){ 
                    $("#apple-popup-modal").modal("openModal");
                });

            }
        );
    </script>

<?php endif;?>