<?php
/**
 * Revered Technologies Pvt. Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://store.reveredtech.com/Revered-LICENSE-COMMUNITY.txt
 *
 ********************************************************************
 * @category   Revered
 * @package    Revered_GuestWishlist
 * @copyright  Copyright (c) Revered Technologies Pvt. Ltd. (http://www.reveredtech.com)
 * @license    http://store.reveredtech.com/Revered-LICENSE-COMMUNITY.txt
 */
// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Sharing $block */
?>
<form class="form wishlist share"
      action="<?= $block->escapeUrl($block->getSendUrl()) ?>"
      id="form-validate"
      method="post"
      data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= $block->escapeHtml(__('Sharing Information')) ?></span></legend><br />
        <div class="field emails required">
            <label class="label" for="email_address"><span><?= $block->escapeHtml(__('Email addresses, separated by commas')) ?></span></label>
            <div class="control">
                <textarea name="emails" cols="60" rows="5" id="email_address" data-validate="{required:true,'validate-emails':true}"><?= /* @noEscape */ $block->getEnteredData('emails') ?></textarea>
            </div>
        </div>

        <div class="field required text">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Your name')) ?></span></label>
            <div class="control">
                <input id="name" name="name" type="text" class="required-entry" value="<?= /* @noEscape */ $block->getEnteredData('name') ?>"/>
            </div>
        </div>

        <div class="field required text">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Your email')) ?></span></label>
            <div class="control">
                <input id="email" type="text" name="email" class="required-entry validate-email"  value="<?= /* @noEscape */ $block->getEnteredData('email') ?>"/>
            </div>
        </div>

        <div class="field text">
            <label class="label" for="message"><span><?= $block->escapeHtml(__('Message')) ?></span></label>
            <div class="control">
                <textarea id="message" name="message" cols="60" rows="5"><?= /* @noEscape */ $block->getEnteredData('message') ?></textarea>
            </div>
        </div>
        <div class="field text">
            <div class="control">
                <?php echo $block->getChildHtml('captcha')?>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?= $block->escapeHtml(__('Share Wish List')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Share Wish List')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
        </div>
    </div>
</form>
