<?php
/**
 * @package     Plumrocket_Base
 * @copyright   Copyright (c) 2020 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license/  End-user License Agreement
 */
?>
<?php /** @var \Plumrocket\Base\Block\Adminhtml\System\Config\Form\Version $block */ ?>
<?php $updates = $block->getNewUpdates(); ?>
<tr>
    <td class="label" colspan="4" style="text-align: left;">
        <div id="pr_info-panel">
            <div class="pr_info-wrapper">
                <span class="pr_module-title"><?= $block->escapeHtml($block->getModuleTitle()) ?> v<?= /* @noEscape */ $block->getVersion() ?></span>
                <div class="pr_subtitle-wrapper">
                    <span class="pr_info-subtitle">developed by</span>
                    <a href="<?= /* @noEscape */ $block->getLogoUrl() ?>" title="Plumrocket Inc." target="_blank">
                        <img src="<?= $block->getViewFileUrl('Plumrocket_Base::images/info_panel/plumrocket_logo.svg') ?>" alt="Plumrocket Inc." width="80" height="15">
                    </a>
                </div>
            </div>
            <div class="pr_buttons-wrapper">
                <a href="<?= $block->getRequestNewFeatureUrl() ?>" class="pr_action-btn pr_btn" target="_blank">
                    <span><?= $block->escapeHtml(__('Request new feature')) ?></span>
                    <span class="pr_image-mask">
                        <img src="<?= $block->getViewFileUrl('Plumrocket_Base::images/info_panel/arrow-btn.svg') ?>" alt="arrow" width="9" height="8">
                    </span>
                </a>
                <?php if ($updates): ?>
                    <a href="<?= $block->getUpdateUrl() ?>" id="pr_new_updates_link" class="pr_link-btn update-btn pr_btn" target="_blank">
                        <span class="pr_icon">
                            <span><?= count($updates) ?></span>
                            <img src="<?= $block->getViewFileUrl('Plumrocket_Base::images/info_panel/updates_icon.svg') ?>" alt="new updates icon" width="18" height="19">
                        </span>
                        <span class="pr_btn-text"><?= count($updates) > 1 ? $block->escapeHtml(__('New updates available')) : $block->escapeHtml(__('New update available')) ?></span>
                    </a>
                <?php else: ?>
                    <span class="pr_link-btn pr_btn">
                        <span class="pr_icon">
                                <img src="<?= $block->getViewFileUrl('Plumrocket_Base::images/info_panel/check-icon.svg') ?>" alt="your extension is up to date" width="15" height="15">
                            </span>
                        <span class="pr_btn-text"><?= $block->escapeHtml(__('Your extension is up to date')) ?></span>
                    </span>
                <?php endif; ?>
                <?php if ($block->getWikiLink()): ?>
                    <a href="<?= $block->escapeUrl($block->getWikiLink()) ?>" class="pr_link-btn pr_btn" target="_blank">
                        <span class="pr_icon">
                            <img src="<?= $block->getViewFileUrl('Plumrocket_Base::images/info_panel/info_icon.svg') ?>" alt="info icon" width="14" height="14">
                        </span>
                        <span class="pr_btn-text"><?= $block->escapeHtml(__('User guide')) ?></span>
                    </a>
                <?php endif; ?>
                <?php if ($rateUsUrl = $block->getRateUsUrl()): ?>
                    <a href="<?= $block->escapeUrl($rateUsUrl) ?>" class="pr_link-btn pr_btn" title="Rate Us" target="_blank">
                        <span class="pr_icon">
                            <img src="<?= $block->getViewFileUrl('Plumrocket_Base::images/info_panel/rate_icon.svg') ?>" alt="rate us icon" width="15" height="15">
                        </span>
                        <span class="pr_btn-text"><?= $block->escapeHtml(__('Rate us')) ?></span>
                    </a>
                <?php endif; ?>
            </div>
        </div>
        <?php if ($updates): ?>
        <script>
            requirejs(['prInfoPanel'], function (prInfoPanel) {
                prInfoPanel.initUpdates('pr_new_updates_link', 'pr_new_updates_content');
            });
        </script>
        <div style="display: none">
            <div id="pr_new_updates_content" class="base-exten-info">
                <?php foreach ($updates as $update): ?>
                    <p class="details-item details-item-ver"><?= $block->escapeHtml(__('Version')) ?> <?= $block->escapeHtml($update['version']) ?></p>
                    <?php foreach ($update['changes'] as $changeLog): ?>
                        <p class="details-item <?= $block->escapeHtml($changeLog['type']) ?>"><?= $block->escapeHtml($changeLog['description']) ?></p>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </div>
        </div>
        <?php endif; ?>
    </td>
</tr>
