<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Amp
 * @copyright   Copyright (c) 2020 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */

use Magento\Catalog\Model\Product\ProductList\Toolbar as ToolbarModel;

?>
<?php if ($block->getCollection()->getSize()): ?>
    <div class="toolbar amp-toolbar-products">
        
        <?php echo $block->getPagerHtml() ?>
        
        <?php if ($block->isExpanded()): ?>
            <div class="toolbar-sorter sorter">
                <select on="change:AMP.navigateTo(url=event.value)">
                
                <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
                    <?php
                    $direction = strtolower($block->getCurrentDirection());
                    if ($block->isOrderCurrent($_key)) {
                        $direction = $direction == 'asc' ? 'desc' : 'asc';
                    }

                    $params = [
                        ToolbarModel::ORDER_PARAM_NAME => $_key,
                        ToolbarModel::DIRECTION_PARAM_NAME => $direction,
                    ];

                    if ($block->getDefaultPerPageValue() !== $block->getLimit()) {
                        $params[ToolbarModel::LIMIT_PARAM_NAME] = $block->getLimit();
                    }

                    ?>
                    <option <?php if($block->isOrderCurrent($_key)): echo "selected"; endif; ?> value="<?php echo $block->getPagerUrl($params) ?>"><?php echo $block->escapeHtml(__($_order)) ?></option>
                <?php endforeach; ?>
                </select>
            </div>

        <?php endif; ?>
    </div>
<?php endif ?>
