<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_AjaxSocialLogin
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
//  @codingStandardsIgnoreFile
?>
<?php
/**
 * @var Bss\SocialLogin\Block\SocialLogin\EnableModule
 */
?>
<?php
if (!$block->isEnable()) {
    return;
}
?>
<form style="display:none;" class="form"
      action="<?php /* @escapeNotVerified */ echo $block->getUrl('sociallogin/account/loginPost') ?>"
      method="post"
      id="sociallogin-login-form"
>
    <input id="sociallogin-login-referer" name="refress-redirect-url" type="hidden" value="" />
    <input id="sociallogin-login-submit" type="submit" value="" />
</form>
