<div class="refer-success-msg">
	<span class="title-1">
		<?= __("Thank you for your referral.") ?>
	</span>
	<span class="title-1">
		<?= __("Coupon Codes are sent within 60 mins . Please check your email for the referral code . In case you have not received your email please check your spam folder or contact ") ?>
        <a href="mailto:care@sololuxury.com">care@sololuxury.com</a><?= __(" for further assistance") ?>
	</span>
	<div class="continue-shop">
		<a class="link-cnt-shop" href="<?php echo $this->getUrl() . 'whats-new'; ?>"><?php echo __("Continue Shopping") ?></a>
	</div>
</div>