<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_AjaxSocialLogin
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
//  @codingStandardsIgnoreFile
?>
<?php

/**
 * @var $block Bss\SocialLogin\Block\SocialLogin\FakeEmail
 */
?>
<?php if ($block->isFakeEmail()) : ?>
    <script type="text/javascript">
        //<![CDATA[
        require([
            'jquery'
        ], function($) {
            $(document).ready(function() {
                $("#form-validate #email").after('<div for="email" class="mage-error" id="email-error" generated="true">Please enter valid email address.</div>');
                $("#form-validate #current-password").val('<?php echo $block->getPass(); ?>').attr('readonly','true');
            });
        });
        //]]>
    </script>
<?php endif ?>
