<?php
    $footer = $this->getConfig('porto_settings/footer');
    $dynamicHelper = $this->helper('\Dynamic\Customization\Helper\Data');
    $storeManager  = $dynamicHelper->getStoreManager();
    $storeCode = $storeManager->getStore()->getCode();
    $storeId = $storeManager->getStore()->getId();
    $siteUrl = $dynamicHelper->getScopeConfig()->getValue("web/secure/base_url");
?>
<div class="footer">
<?php
    if( $footer['footer_top'] ){
?>
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                <?php
                    $area = 'footer_top_block';
                    $type = $footer[$area];
                    if( $type == 'custom' && $footer['footer_top_custom'] ){
                        $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                        if($block) {
                            $block->setBlockId($footer['footer_top_custom']);
                        }
                        if($block){
                            echo '<div class="custom-block">'.$block->toHtml().'</div>';
                        }
                    }

                ?>


                </div>
            </div>
        </div>
    </div>
<?php
    }
    if( $footer['footer_middle'] ){
?>
    <div class="footer-middle cfooter-content-wrapper">
        <div class="container">
        <?php
            if( $footer['footer_ribbon'] ){
        ?>
            <div class="footer-ribbon">
                <span><?php echo $footer['footer_ribbon_text'] ?></span>
            </div>
        <?php
            }
        ?>
            <div class="row">
                <?php
                    for( $i = 1; $i <= 4; $i++ ){
                        $area = 'footer_middle_column_'.$i;
                        $type = $footer[$area];
                        if( $type ){
                            echo '<div class="col-lg-'.$footer[$area.'_size'].'">';
                        }
                        if( $type == 'custom' && $footer[$area.'_custom'] ){
                            $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                            if($block) {
                                $block->setBlockId($footer[$area.'_custom']);
                            }
                            if($block){
                                echo $block->toHtml();
                            }
                        }
                        if( $type == 'newsletter' ){
                            echo $this->getChildHtml('footer.newsletter');
                        }
                        if( $type ){
                            echo '</div>';
                        }
                    }
                ?>
                <div class="col-lg-2">
                <div class="block footer-subscribe">
                    <div class="footer-messages">
                        <div id="result-newsletter"></div>
                    </div>
                    <input type="text" placeholder="<?php echo __('Your email') ?>" id="newsletter">
                    <span class="sub-bttn"><?php echo __('Subscribe') ?></span>
                </div>
                </div>
            </div>
        </div>
    </div>
<?php
    }
    if( $footer['footer_middle_2'] ){
?>
    <div class="footer-middle footer-middle-2">
        <div class="container 123">
            <div class="row">
            <?php
                for( $i = 1; $i <= 4; $i++ ){
                    $area = 'footer_middle_2_column_'.$i;
                    $type = $footer[$area];
                    if( $type ){
                        echo '<div class="col-lg-'.$footer[$area.'_size'].'">';
                    }
                    if( $type == 'custom' && $footer[$area.'_custom'] ){
                        $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                        if($block) {
                            $block->setBlockId($footer[$area.'_custom']);
                        }
                        if($block){
                            echo $block->toHtml();
                        }
                    }
                    if( $type == 'newsletter' ){
                        echo $this->getChildHtml('footer.newsletter');
                    }
                    if( $type ){
                        echo '</div>';
                    }
                }
            ?>
            </div>
        </div>
    </div>
<?php
    }
    if( $footer['footer_bottom'] ){
?>
    <div class="footer-bottom">
        <div class="container">
            <?php
            if($footer['footer_logo_src']){

                $url = $this->getFooterLogoSrc();
            ?>
            <?php if ($this->isHomePage()):?>
                <strong class="logo">
            <?php else: ?>
                <a class="logo" href="<?php echo $this->getUrl(''); ?>" title="">
            <?php endif; ?>
                <img src="<?php echo $url ?>" alt=""/>
            <?php if ($this->isHomePage()):?>
                </strong>
            <?php else:?>
                </a>
            <?php endif?>
            <?php
            }
            if($footer['footer_bottom_custom_1']){
                $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                if($block) {
                    $block->setBlockId($footer['footer_bottom_custom_1']);
                }
                if($block){
                    echo '<div class="custom-block">'.$block->toHtml().'</div>';
                }
            }
            ?>
            <?php
            if($footer['footer_bottom_custom_2']){
                $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                if($block) {
                    $block->setBlockId($footer['footer_bottom_custom_2']);
                }
                if($block){
                    echo '<div class="custom-block f-right">'.$block->toHtml().'</div>';
                }
            }
            ?>
            <address><?php echo $footer['footer_bottom_copyrights'] ?></address>
            <?php if($footer['footer_store_switcher']) echo $this->getChildHtml("footer.store_switcher"); ?>
        </div>
    </div>
<?php
    }
?>
</div>
<a href="javascript:void(0)" id="totop"><em class="porto-icon-up-open"></em></a>

<script type="text/javascript">

require([
  'jquery',
  'jquery/ui',
  'mage/translate'
  ], function($){
  $(document).ready(function() {
      var storeName = '<?php echo $storeCode ?>';
      var storeId = '<?php echo $storeId ?>';
      $('.footer-subscribe span').click(function(){
        // $('.footer-messages').show();
        // $('.footer-messages').delay(10000).fadeOut();
        var custEmail = $("#newsletter").val();
        if(custEmail == ''){
          $("#result-newsletter").text('Email is required');
          //$('#result-newsletter').delay(8000).fadeOut(800);
        }
        else if (!validateEmail(custEmail)) {
          $("#result-newsletter").text('Please enter valid email address');
          //$('#result-newsletter').delay(8000).fadeOut(800);
        }
        else{
          // console.log(email);
           $("#result-newsletter").text('').css({"display":"block"});
            $.ajax({
                url: "<?php echo $siteUrl ?>newsletter/subscriber/new",
                type: "POST",
                data: {
                  email: custEmail
                },
                dataType: "JSON",
                beforeSend: function() {
                     $('span.sub-bttn').empty();
                     $("span.sub-bttn").addClass("news-loading").removeClass("sub-bttn");
                  },
                  complete: function(){
                      setTimeout(function() {
                        $("span.news-message").addClass("sub-bttn").removeClass("news-message");
                        $("span.sub-bttn").text("Subscribe");
                    }, 5000); 
                   
                     //$('#result').fadeIn(800);
                  },
                success: function (jsonStr) {
                     // alert($.mage.__(jsonStr['message']));
                     var message = jsonStr['message'];
                     // $("#result-newsletter").text(JSON.stringify(jsonStr));
                    //  console.log(message);
                     // console.log(jsonStr['message']);=
                    $("span.news-loading").addClass("news-message").removeClass("news-loading");
                    $("span.news-message").text(message);

                    // $("#result").text(JSON.stringify(jsonStr));
               },
               error: function(data) {
                $("span.news-loading").addClass("news-message").removeClass("news-loading");
                $(".news-message").text("Please try after some time");
               }
            });
        }


      });

  });

  function validateEmail($email) {
    var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
    return emailReg.test($email);
  }

});
 </script>