<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Checkout
 */
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()) :?>
        <div class="success-messages">
            <?php if ($block->getCanViewOrder()) :?>
                <h2 class="success-title"><?php echo __('Thank You For Your Purchase!') ?></h2>
                <p><?= $block->escapeHtml(__('Your order number is:')) ?>
                    <a href="<?= /* @noEscape */$block->getViewOrderUrl() ?>"
                       class="order-number">
                        <strong>
                            <?= /* @noEscape */$block->getOrderId() ?>
                        </strong>
                    </a>
                </p>
            <?php  else : ?>
                <p>
                    <?= $block->escapeHtml(__('Your order # is:')) ?>
                    <span>
                        <?= /* @noEscape */$block->getOrderId() ?>
                    </span>
                </p>
            <?php endif;?>
        </div>
		 <?= $block->getChildHtml('details') ?>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>
    <?= $block->getChildHtml('cms') ?>

    <div class="actions-toolbar">
		<a class="btn-trackorder" href="<?php echo '/sales/order/view/order_id/'.$block->getOrderId() ?>"><?php echo __('Track Order') ?></a>
        <div class="primary">
            <a class="action primary continue" href="<?= /* @noEscape */$block->getUrl() ?>">
                <span><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        </div>
    </div>
</div>
