<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$continueshoppingHelper = $this->helper('Ludxb\Continueshopping\Helper\Data');
 ?>
 <input type="hidden" name="lastvisitedurl" value="<?= $continueshoppingHelper->getLastUrl() ?>">
 
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php $dailydealhelper=$this->helper('Smartwave\Dailydeals\Helper\Data'); ?>
<?php 
$dynamicHelper = $this->helper('\Dynamic\Customization\Helper\Data');
$storeManager  = $dynamicHelper->getStoreManager();

$customerSession = $dynamicHelper->getCustomerSessionManager();
$customerName = $customerEmail = '';
if ($customerSession->isLoggedIn()) {
    $customerSession->getCustomerId();  // get Customer Id
    $customerSession->getCustomerGroupId();
    $customerSession->getCustomer();
    $customerSession->getCustomerData();

    $customerName = $customerSession->getCustomer()->getName();  // get  Full Name
    $customerEmail = $customerSession->getCustomer()->getEmail(); // get Email
}

$storeCode = $storeManager->getStore()->getCode();
$siteUrl = $dynamicHelper->getConfig("web/secure/base_url");

$currency = $dynamicHelper->getCurrency();
$currencysymbol = $currency->getCurrencySymbol();
$productSku = $_product->getSku();
$productPrice = $_product->getFinalPrice();
$productName = $_product->getName();

?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <?php if($block->getRequest()->getParam('dailydealproduct') || $dailydealhelper->isDealProduct($_product->getId())) : ?>
       <?php $productSku=$_product->getSku(); ?>
    <input type="text" id="todate" value="<?php echo $dailydealhelper->getDailydealToDate($productSku); ?>" style="display:none;" >
    <input type="text" style="display: none;" id="fromdate" value="<?php echo $dailydealhelper->getDailydealFromDate($productSku); ?>">
    <p id="countdown"></p>
    <div class="sw-dailydeal-wrapper">
      <div class="sw-dailydeal">
        <?php if($block->getRequest()->getParam('dailydealproduct')) :?>
            <p id="expired"></p>
        <?php endif; ?>
        <div class="countdowncontainer" style="display:none;">
            <span class="dailydeal-label">
                <?php echo __('Offer Ends In:'); ?>
            </span>
            <span class="number-wrapper">
                <div class="line"></div>
                <span class="number day"><p id="countdown_days"></p></span>
                <div class="caption"><?php echo __('Days'); ?></div>
            </span>

            <span class="number-wrapper">
                <div class="line"></div>
                <span class="number hour"><p id="countdown_hours"></p></span>
                <div class="caption"><?php echo __('Hours'); ?></div>
            </span>

            <span class="number-wrapper">
                <div class="line"></div>
                <span class="number min"><p id="countdown_minutes"></p></span>
                <div class="caption"><?php echo __('Minutes'); ?></div>
            </span>

            <span class="number-wrapper">
                <div class="line"></div>
                <span class="number sec"><p id="countdown_seconds"></p></span>
                <div class="caption"><?php echo __('Seconds'); ?></div>
            </span>
        </div>
      </div>
    </div>
    <?php endif; ?>
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?>:</span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
                <div class="qty-changer">
                    <a href="javascript:void(0)" class="qty-inc"><i class="porto-icon-up-dir"></i></a>
                    <a href="javascript:void(0)" class="qty-dec"><i class="porto-icon-down-dir"></i></a>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><i class="fa fa-shopping-cart" aria-hidden="true"></i><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <!-- START CODE FOE WISTLIST BUTTON -->
            
            <!-- END CODE FOE WISTLIST BUTTON -->
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>

<a href="#" class="action towishlist primary cls_wishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add To Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
            <span><?php /* @escapeNotVerified */ echo __('<i class="fa fa-heart" aria-hidden="true"></i>') ?><?php /* @escapeNotVerified */ echo "Add to Wish List" ?></span>
            </a>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Magento_Catalog/js/catalog-add-to-cart'
    ], function ($) {
        'use strict';

        $('#product_addtocart_form').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {
                var widget = $(form).catalogAddToCart({
                    bindSubmit: false
                });

                widget.catalogAddToCart('submitForm', $(form));

                return false;
            }
        });
    });
</script>
<?php endif; ?>

<!-- script to send data to ERP for wishlist -->
<?php if(!empty($customerName)): ?>
<script type="text/javascript">
require(['jquery', 'jquery/ui'], function($){
  $(document).ready(function() {

    var fileUrl = '<?php echo $siteUrl ?>apifiles/wishlistcreate.php';

     $('a.towishlist').click(function(){
        
         
          $.ajax({
              url: fileUrl,
              type: "POST",
              data: {
                website:"WWW.SOLOLUXURY.COM",
                product_sku: '<?php echo $productSku ?>',
                customer_name: '<?php echo $customerName ?>',
                customer_email: '<?php echo $customerEmail ?>',
                lang_code : '<?php echo $storeCode ?>',
                product_name: '<?php echo $productName ?>',
                product_price: '<?php echo $productPrice ?>', 
                product_currency: '<?php echo $currencysymbol ?>'
                
             },
              dataType: "JSON",
              beforeSend: function() {
               },
               complete: function(){
               },
              success: function (jsonStr) {
                   var status = jsonStr['status'];
                   var message = jsonStr['message'];
                   var data = JSON.stringify(jsonStr);
                   var obj = JSON.parse(data);
                   var errors = obj.errors;
                   if(errors){
                    $.each( errors, function( key, value ) {
                        // alert(key + " : " + value);
                   });
                     
                   }
                   else{
                        // alert(message);
                    }
                  
             }


          });

      });

  });
});

</script>
<?php endif; ?>
<!-- end -->

<script type="text/javascript">
require([
    'jquery'
], function ($) {
// Timer for LEFT time for Dailydeal product
    var _second = 1000;
    var _minute = _second * 60;
    var _hour = _minute * 60;
    var _day = _hour * 24;
    var timer;

    function showRemaining(currentdate) {
      var cid='countdown';
      var startdateid='fromdate';
      var id='todate';
      var daysid='countdown_days';
      var hoursid='countdown_hours';
      var minutesid='countdown_minutes';
      var secondsid='countdown_seconds';

      var enddate = new Date($('#'+id).val());
      var dealstartdate=new Date($('#'+startdateid).val());

      // Get Current Date from magentodatetime
      var currentdate=new Date(currentdate);

      //Get Difference between Two dates
      var distance = enddate - currentdate;

      if (distance < 0) {
        $('#expired').html("<div class='offermessage' >EXPIRED!</div>");
      } else if(dealstartdate > currentdate) {
        $('.countdowncontainer').hide();
        var msg="<div class='offermessage' > Coming Soon..<br>Deal Start at:<br>"+$('#'+startdateid).val()+"</div>";
        $('#expired').html(msg);
      } else {
        var days = Math.floor(distance / _day);
        var hours = Math.floor((distance % _day) / _hour);
        var minutes = Math.floor((distance % _hour) / _minute);
        var seconds = Math.floor((distance % _minute) / _second);
        if(hours < 10)
            hours = "0" + hours;
        if(minutes < 10)
            minutes = "0" + minutes;
        if(seconds < 10)
            seconds = "0" + seconds;
        $('.countdowncontainer').show();
        $('#'+daysid).html(days);
        $('#'+hoursid).html(hours);
        $('#'+minutesid).html(minutes);
        $('#'+secondsid).html(seconds);
      }
    }

    //Set date as magentodatetime
    var date = new Date('<?php echo $dailydealhelper->getcurrentDate() ?>');

    var day   = date.getDate();
    var month = date.getMonth();
    var year  = date.getFullYear();
    var hours = date.getHours();
    var minutes = "0" + date.getMinutes();
    var seconds = "0" + date.getSeconds();

    var fulldate = year+'-'+(month+1)+'-'+day+' '+hours + ':' + minutes.substr(minutes.length-2) + ':' + seconds.substr(seconds.length-2);

    // Set Interval
    timer = setInterval(function()
    {
        date.setSeconds(date.getSeconds() + 1);
        var month=date.getMonth();
        var currentdatetime=date.getFullYear()+"-"+(month+1)+"-"+date.getDate()+" "+date.getHours()+":"+date.getMinutes()+":"+date.getSeconds();
        showRemaining(currentdatetime);
    }, 1000);
});
</script>
<?php
if($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE){

$sizeHelper = $this->helper("Dynamic\SizeApi\Helper\Data");
$categoryIds = $_product->getCategoryIds();
$attributeData = $sizeHelper->getAttributeData($categoryIds);

$productTypeInstance = $dynamicHelper->getProductTypeInstanceManager();
$productAttributeOptions = $productTypeInstance->getConfigurableAttributesAsArray($_product);


$tmp_option = array();
foreach ($productAttributeOptions as $key => $value) {
	 $tmp_option[$key]['options'] = $value['options'];
	 $tmp_option[$key]['name'] = $value['label'];
    
}

$userContext = $dynamicHelper->getHttpManager();
$isLoggedIn = $userContext->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);

?>
<!-- Special Request -->
<div class="clsspecialreqpop">
	<div id="myModalspecsize" class="modal">
	  	<div class="modal-content">
	    	<span class="close" id="myModalspecsizeclose">&times;</span>
	    	<h3 class="clsspecialpopupheading"><?php echo __('Special Size Requests') ?></h3>
	    	<form class="form contact cls_popupsizerequest_form"
              action=""
              id="contact-form"
              method="post"
              data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
              data-mage-init='{"validation":{}}'>
				<?php if(!$isLoggedIn) { ?>
                    <div class="field name required cls_comm_input">
                        <div class="control"><input id="email" class="input-text" title="Email" name="email" type="email" value="" placeholder="<?php echo __('Enter email')?>"></div>
                    </div>
                <?php } else { ?>
                    <input id="email" class="input-text notifyme-email" title="Email" name="email" type="hidden" value="<?php echo $customerEmail; ?>">
                <?php } ?>
				<?php if(!empty($attributeData) && count($attributeData) > 0) { ?>
                    <div class="field name required cls_comm_input">
                        <div class="control">
                            <label class="select_label" for="dropdown">Select <?php echo __("size"); ?></label>
                            <select id="selectedsize" class="input-text" title="<?php echo __("size"); ?>" name="<?php echo __("size"); ?>">
                                <?php foreach ($attributeData as $attribute) { ?>
                                    <option value='<?php echo $attribute; ?>'><?php echo $attribute; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                <?php } else { ?>
                    <?php foreach( $tmp_option as $key=>$ovalue){ ?>
                        <div class="field name required cls_comm_input">
                            <div class="control">
                                <label class="select_label" for="dropdown">Select <?php echo $ovalue['name']; ?></label>
                                <select id="selectedsize" class="input-text" title="<?php echo $ovalue['name']; ?>" name="<?php echo $ovalue['name']; ?>">
                                    <?php 
                                    foreach ($ovalue['options'] as $okey => $tmp) 
                                    { ?>
                                        <option value='<?php echo $tmp['label']; ?>'><?php echo $tmp['label']; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    <?php } ?>
                <?php } ?>
				<input id="productsku" class="input-text" title="Product Sku" name="productsku" type="hidden" value="<?php echo $_product->getSku(); ?>">
				<div class="field name required spBtn"> 
					<div class="control">
						<input type="hidden" name="hdn_subject" id="hdn_subject" value="" />
						<input type="hidden" name="hdn_message" id="hdn_message" value="" />
						<div class="mm-action"><span id="btn_sizesubmit" class="btn btn-custom"><?php echo __('Submit')?></span></div>
					</div>
				</div>
			</form>
	  	</div>
	</div>
</div>
<div class='clsmsgsuccessbox' >
	<div id="myModalspecsizeSuccess" class="modal">
	  	<div class="modal-content">
	    	<span id="specsizesucessClose" class="close" style="display:none">&times;</span>
        <p id="loader-message"><?php echo __('loading')?></p>
        <p id="result-message"></p>
		<div id="specsizesucessClosebtn"><span class="btn btn-close"><?php echo __('Close')?></span></div>
	  	</div>
	</div>
</div>
<script type="text/javascript">
require(['jquery', 'jquery/ui'], function($){

  $(document).ready(function() {
		
		 var existCondition = setInterval(function() {
		   if ($("#product-options-wrapper .fieldset").length > 0 && $("#attribute167").length > 0 && $("#attribute167 option").length > 1) { 
			clearInterval(existCondition);
			runMyFunction();
		   }
		  }, 100);
		  
		function runMyFunction(){
						$('#attribute167').append('<option value="notfound">Size missing? Be notified when it is back in</option>');
				
		}
		$('#attribute167').on('change', function() {
			var thistext = $(this).find("option:selected").text();
			
			 if(this.value == "notfound")
			 {
				var modal1 = document.getElementById("myModalspecsize");
				modal1.style.display = "block";
				$('#attribute167').val("");
				var mymodalspecsizeclose = document.getElementById("myModalspecsizeclose");
				mymodalspecsizeclose.onclick = function() {
				  modal1.style.display = "none";
				}
				
			 }else if(thistext.indexOf("Sold Out") != -1)
			 {
				var modal1 = document.getElementById("myModalspecsize");
				modal1.style.display = "block";
				var mymodalspecsizeclose = document.getElementById("myModalspecsizeclose");
				mymodalspecsizeclose.onclick = function() {
				  modal1.style.display = "none";
				}
			}
		 });
		
			
		
   });
});

</script>
<script type="text/javascript">

require([
    'jquery',
], function ($)
{
    $(document).ready(function(){
      var fileUrl = '<?php echo $siteUrl ?>apifiles/specialsizerequest.php';
    	var modal1 = document.getElementById("myModalspecsize");
    	var myModalspecsizeSuccess = document.getElementById("myModalspecsizeSuccess");
		
		var mymodalspecsizeclose = document.getElementById("myModalspecsizeclose");
		var specsizesucessClose = document.getElementById("specsizesucessClose");

		specsizesucessClose.onclick = function() {
		  	myModalspecsizeSuccess.style.display = "none";
		}
		var specsizesucessClosebtn = document.getElementById("specsizesucessClosebtn");

		specsizesucessClosebtn.onclick = function() {
		  	myModalspecsizeSuccess.style.display = "none";
		}
		mymodalspecsizeclose.onclick = function() {
		  modal1.style.display = "none";
		}
		window.onclick = function(event) {
		  if (event.target == modal1) {
		    modal1.style.display = "none";
		  }
		}

        var url = "<?php echo $this->getUrl('notifyme/index/post'); ?>";

        $('#btn_sizesubmit').click(function(){
          var email = $("#email").val();
          var size = $("#selectedsize").val();
          var productsku = $("#productsku").val();
          $("#result-message").text('');
          $('#myModalspecsize').css({"display":"none"});
          $('#myModalspecsizeSuccess').css({"display":"block"});
          $.ajax({
                url: url,
                type: "POST",
                data: {
                  email: email,
                  product_sku: productsku,
                  product_size: size
                },
                dataType: "JSON",
                beforeSend: function() {
                    $('#loader-message').show();
                },
                complete: function(){
                    $('#loader-message').hide();
                },
                success: function (response) {
                     if(response.errors == false) {
                        $("#result-message").html(response.message);
                    } else {
                        $("#result-message").html(response.message);
                    }
                }
            });
        });

    });
});
</script>
<!-- Special Request -->
<?php } ?>