<?php $_product = $block->getProduct(); ?>

<div class="price-match-main">
    <div class="price-match-model">
        <div class="match-content">
        </div>
        <div class="clsspecialreqpop">
            <div id="myModal-price-match" class="modal" style="display: none">
                <div class="modal-content clsspecialpopupheading">
                    <span class="close">&times;</span>
                    <h3 class="PriceMatchModalContent-title"><?php echo __("Best Price Promise"); ?></h3>
                    <div class="PriceMatchModalContent-slogan"><?php echo __("Your Best Price - Always."); ?></div>
                    <div class="PriceMatchModalContent-description"><?php echo __("If your preferred item is lower priced at any other store at the current time we will match the price and offer you 10% additional store credit for your next purchase."); ?>
                    </div>
                    <span><?php echo __("Simply let us know by "); ?><a class="UniversalLink" id="price-match-create-ticket-bth" data-buy="no" rel="noopener noreferrer" style="cursor: pointer"><?php echo __("clicking here"); ?>.</a></span>
                    <div class="PriceMatchModalContent-separator"></div>
                    <a class="UniversalLink PriceMatchModalContent-postPurchaseTitle" id="price-match-already-made-create-ticket-bth" data-buy="yes" target="_blank" style="cursor: pointer" rel="noopener noreferrer"><?php echo __("Already Made your Purchase."); ?></a>
                    <span><?php echo __("Dont Worry let us know by "); ?><a class="PriceMatchModalContent-postPurchaseInstructions" href="/contact-us?initialContactTypeCode=priceMatch" target="_blank"><?php echo __("clicking here"); ?></a><?php echo __(" and we our customer support team will refund you the difference if the purchase was made within the last 30 days."); ?></span>
                    
                    <div class="PriceMatchModalContent-separator"></div>
                    <div class="PriceMatchModalContent-terms">
						<span><?php echo __("Please see T & C by "); ?><a href="/terms-and-conditions" class="UniversalLink" target="_blank" rel="noopener noreferrer"><?php echo __("clicking here"); ?>.</a></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="price-match-btn-content">
        <a href="javascript:void(0);" id="myspecialricematch" class="btn price-mathc-btn" data-product-sku="<?php echo $_product->getSku(); ?>"><?php echo __("Price match"); ?></a>
    </div>
</div>