<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Amp
 * @copyright   Copyright (c) 2019 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>
<?php
/** @var \Plumrocket\Amp\Block\Catalog\Category\Image $block */

/** @var \Magento\Catalog\Helper\Output $outputHelper */
$outputHelper    = $this->helper(\Magento\Catalog\Helper\Output::class);

if ($categoryImage = $block->createCategoryImage()) {
    $imgHtml = $outputHelper->categoryAttribute($block->getCurrentCategory(), $categoryImage->toHtml(), 'image');
} else {
    $imgHtml = '';
}
?>
<?php /* @escapeNotVerified */ echo $imgHtml ?>
