<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Amp
 * @copyright   Copyright (c) 2019 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>
<?php /** @var \Magento\Backend\Block\Template $block */ ?>
<div class="admin__field-note">
    <?= __(
        'You can learn more about AMP HTML specification and text formatting %1here%2',
        '<a href="https://www.ampproject.org/docs/fundamentals/spec" target="_blank" rel="noopener">',
        '</a>'
    ) ?>
</div>
