<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    BSS_HtmlSiteMap
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/**
 * SEO Toolbar template
 *
 * @var $block Bss\HtmlSiteMap\Block\ItemsCollection
 */
?>
<?php
$helper = $block->getHelper();
$baseUrl = $helper->getBaseUrl();
$getEnable = $helper->isEnable();
$urlKey = $helper->getModuleRoute();
$titleSiteMap = $helper->getTitleSiteMap();
$showLinkAt = $helper->getShowLinkAt();
?>
<?php if ($getEnable && $showLinkAt === 'top') : ?>
    <li>
        <a href="<?php echo $baseUrl . $urlKey; ?>"><?php echo $block->escapeHtml($titleSiteMap); ?></a>
    </li>
<?php
endif;
