<?php
/**
 * @var Custom\RedirectContactus\Block\Success $block
 */
$RedirectHelper = $this->helper('\Custom\RedirectContactus\Helper\Data');
$storeManager = $RedirectHelper->getStoreManager();
$baseUrl = $RedirectHelper->getBaseUrl();
$customerSession = $RedirectHelper->getCustomerSessionManager();

?>
<div class="cls_contactus_main">
    <center>
    <p class="contact-form__description"><?php echo __("We'll Get In Touch Soon.") ?></p>
        <div class='message'>We have received your Request & We'll Get in Touch Soon. You can view responses on your email & under My Tickets.</div>
        <a href="<?php echo $baseUrl?>" title="home" role="button">
            <button type="submit" name="btncontactus" title="<?php /* @escapeNotVerified */ echo __('Continue Shopping ') ?>" class="action submit primary">
        <span><?php /* @escapeNotVerified */ echo __('Continue Shopping ') ?></span>
            </button>
        </a>
        <?php if ($block->customIsLoggedIn()) {?>
            <a href="<?php echo $baseUrl.'tickets/customer/index/'?>" title="Tickets" role="button">
                <button type="submit" name="btncontactus" title="<?php /* @escapeNotVerified */ echo __('My Tickets') ?>" class="action submit primary">
                    <span><?php /* @escapeNotVerified */ echo __('My Tickets') ?></span>
                </button></a>
    <?php } else { ?>
        <a href="<?php echo $baseUrl.'customer/account/login/'?>" title="Login" role="button">
            <button type="submit" name="btncontactus" title="<?php /* @escapeNotVerified */ echo __('Login') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('Login') ?></span></button>
        </a> <?php }?>
    </center>
</div>