<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Amp
 * @copyright   Copyright (c) 2019 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>
<?php /** @var \Plumrocket\Amp\Block\Catalog\Product\ListForm $block */ ?>

<form method="post"
      action-xhr="<?= $block->getActionUrl() ?>"
      target="_top"
      on="<?= $block->getFormMessageEvents() ?>"
      id="<?= $block->getFormId() ?>"
>
    <?php /** Use ajax param for disable form_key validation */ ?>
    <input type="hidden" name="ajax" value="1"/>
    <input type="hidden" name="product" [value]='<?= $block->getProductIdStatePath() ?>' value="0"/>

    <?= $block->getAmpMessagesBlock()->toHtml() ?>
</form>