<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Amp
 * @copyright   Copyright (c) 2020 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */

use Magento\Catalog\Model\Product\ProductList\Toolbar as ToolbarModel;

?>
<?php if ($block->getCollection()->getSize()): ?>
    <div class="toolbar amp-toolbar-products">
        <p class="toolbar-amount">
            <?php if ($block->getLastPageNum() > 1): ?>
                <?php /* @escapeNotVerified */ echo __('Items %1-%2 of %3',
                    '<span class="toolbar-number">' . $block->getFirstNum() . '</span>',
                    '<span class="toolbar-number">' . $block->getLastNum() . '</span>',
                    '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
            <?php elseif ($block->getTotalNum() == 1): ?>
                <?php /* @escapeNotVerified */ echo __('%1 Item',
                    '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
            <?php else: ?>
                <?php /* @escapeNotVerified */ echo __('%1 Items',
                    '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
            <?php endif; ?>
        </p>
        <?php echo $block->getPagerHtml() ?>

        <div class="field limiter">
            <label class="label" for="limiter">
                <span><?php /* @escapeNotVerified */ echo __('Show') ?></span>
            </label>
            <div class="control">
                <div class="limiter-options">
                    <?php foreach ($block->getAvailableLimit() as $_key => $_limit) : ?>
                        <?php if ($this->isLimitCurrent((string)$_limit)) : ?>
                            <?php /* @escapeNotVerified */ echo $_limit ?>
                        <?php else : ?>
                            <a href="<?php echo $block->getPagerUrl([ToolbarModel::LIMIT_PARAM_NAME => $_key]) ?>"><?php /* @escapeNotVerified */ echo $_limit ?></a>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            </div>
            <span class="limiter-text"><?php /* @escapeNotVerified */ echo __('per page') ?></span>
        </div>

        <?php if ($block->isExpanded()): ?>
            <div class="toolbar-sorter sorter">
                <label class="sorter-label" for="sorter"><?php /* @escapeNotVerified */ echo __('Sort By') ?></label>
                <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
                    <?php
                    $direction = strtolower($block->getCurrentDirection());
                    if ($block->isOrderCurrent($_key)) {
                        $direction = $direction == 'asc' ? 'desc' : 'asc';
                    }

                    $params = [
                        ToolbarModel::ORDER_PARAM_NAME => $_key,
                        ToolbarModel::DIRECTION_PARAM_NAME => $direction,
                    ];

                    if ($block->getDefaultPerPageValue() !== $block->getLimit()) {
                        $params[ToolbarModel::LIMIT_PARAM_NAME] = $block->getLimit();
                    }

                    ?>
                    <a class="sort-product <?php if($block->isOrderCurrent($_key)): ?> sorter-active<?php endif; ?>" href="<?php echo $block->getPagerUrl($params) ?>">
                        <?php echo $block->escapeHtml(__($_order)) ?></a>
                <?php endforeach; ?>
                <?php if ($block->getCurrentDirection() == 'desc'): ?>
                    <a class="sort-by-switcher sort-desc" title="<?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?>"
                       href="<?php echo $block->getPagerUrl([ToolbarModel::DIRECTION_PARAM_NAME => 'asc']) ?>">
                        <span><?php /* @escapeNotVerified */ echo __('↑ (asc)') ?></span>
                    </a>
                <?php else: ?>
                    <a class="sort-by-switcher sort-asc" title="<?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?>"
                       href="<?php echo $block->getPagerUrl([ToolbarModel::DIRECTION_PARAM_NAME => 'desc']) ?>">
                        <span><?php /* @escapeNotVerified */ echo __('↓ (desc)') ?></span>
                    </a>
                <?php endif; ?>
            </div>

        <?php endif; ?>
    </div>
<?php endif ?>
