<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_AjaxSocialLogin
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
//  @codingStandardsIgnoreFile
?>
<?php $helper = $this->helper('Bss\SocialLogin\Helper\Data'); ?>
<div class="block-container forgot" style="display:none" id="tab-forgot-pw">
    <div class="block-content">
        <form class="form-password-forget"
              id="social-form-password-forgot"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */
            echo __('* Required Fields') ?>">
                <div class="field note"><?php /* @escapeNotVerified */
                    echo __('Please enter your email address below to receive a password reset link.'); ?></div>
                <div class="field email required">
                    <label for="email_address" class="label"><span><?php /* @escapeNotVerified */
                            echo __('Email') ?></span></label>

                    <div class="control">
                        <input type="email" name="email" alt="email" id="email_address" class="input-text"
                               value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>"
                               data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <?php echo $block->getChildHtml('form_additional_info'); ?>
                
                <!-- recaptcha -->
                <?php if ($helper->recaptcha('fogot-pasw')) : ?>
                <div class="recaptcha field required" style="overflow:hidden;position:relative;margin-bottom:10px;">
                    <div id="tab-fogot-recaptcha"></div>
                    <input type="text" id="fogot-recaptcha" name="fogot-recaptcha" value="" class="bss-recaptcha" data-validate="{required:true, 'required-entry':true}" readonly style="visibility:hidden; position:absolute; left:-1000000px" />
                </div>
                <?php endif; ?>

            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="button" class="action send primary" id="bt-social-fogot"><span><?php /* @escapeNotVerified */
                            echo __('Submit') ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>
