<?php
/**
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

?>
<div class="mb-ajaxsuite-popup-wrapper" id="mb-ajaxsuite-popup-wrapper">
    <a id="mb-ajaxsuite-close" class="mb-ajaxsuite-close"></a>
    <?= $block->getChildHtml('ajaxsuite.popup.popup'); ?>
</div>
<div class="mb-ajaxsuite-blank" id="mb-ajaxsuite-blank"></div>
