<?php
$itemCollections = $block->getMyTicketsCollection();
$ticketTypes = array();
$ticketTypes[0] = __('N/A');
$ticketTypes[1] = __('Special Request');
$ticketTypes[2] = __('Item Return Request');
$ticketTypes[3] = __('Order Cancel Request');
$ticketList = '';
$ticketreply = "";
$dynamicHelper = $this->helper('\Dynamic\Customization\Helper\Data');
$storeManager = $dynamicHelper->getStoreManager();
$baseUrl = $dynamicHelper->getBaseUrl();
?>
<div class="mytickets-container">
  <div class="row">
    <div class="col-md-12">
      <h2><?php echo __('My Tickets') ?></h2>
    </div>
  </div>
  <div class="row">
      <div class="col-md-12" id="ticketresult-message"></div>
   </div>
  <div class="desktop-view">
  <div class="row">
    <div class="col-md-12">
      <ul class="titles test">
        <li><?php echo __('ID') ?></li>
        <li><?php echo __('Name') ?></li>
        <li><?php echo __('Type') ?></li>
        <li><?php echo __('Created') ?></li>
        <li><?php echo __('Message') ?></li>
        <li><?php echo __('Current Status') ?></li>
        <li><?php echo __('Action') ?></li>
      </ul>
      <div class="ticket-content">
		  <?php if( $itemCollections && $itemCollections->getSize()){?>
			  <?php foreach($itemCollections as $item){?>
				  <?php $ticketCode = $item->getTicketCode();?>
			   <ul>
				   <li><?php echo ($ticketCode!='')?$ticketCode:__('Ticket id Shall be Updated Shortly');?></li>
				   <li><?php echo $item->getName().' '.$item->getLastName();?></li>
				   <li><?php echo $ticketTypes[$item->getTicketType()] ;?></li>
				   <li><?php echo $item->getCreatedAt();?></li>
				   <li><?php echo $item->getRemarks();?></li>
				   <li><?php echo  ($item->getStatus()==1)? __('Active'): __('Inactive');?></li>
				   <?php if(isset($ticketCode) && $ticketCode!=''){?>
				         <li class="text-center"><a class="porto-icon-eye showticketmessage" data-tcode="<?php echo $ticketCode;?>" data-tid="<?php  echo $item->getMyticketsId()?>">View</a>
				    <?php }else {?>
						 <li class="text-center"><a class="showticketnomessage" data-tcode="<?php echo $ticketCode;?>" data-tid="<?php  echo $item->getMyticketsId()?>">View</a>
						<?php }?>
				   </li>

			   </ul>
			  <?php }?>

           <?php } else {?>
			   <ul>
				   <li><?php echo __('No Records Found'); ?></li>
			   </ul>
		   <?php }?>
        </div>
    </div>
  </div>
  </div>
  <!--Start Mobile View-->
  <div class="mobile-view">
	  <div class="row">
		  <div class="col-md-12">
			  <br /><br /><br /><br /><br /><br /><br /><br /><br />
		  </div>

	  </div>

		<div class="row">
			<div class="col-md-12">
				<ul class="titles">
					<li><?php echo __('ID') ?></li>
					<li><?php echo __('Message') ?></li>
					<li class="text-center"><?php echo __('Action') ?></li>
				</ul>
				<div class="ticket-content">
					<?php if( $itemCollections && $itemCollections->getSize()){?>
			  <?php foreach($itemCollections as $item){?>
				  <?php $ticketCode = $item->getTicketCode();?>
			   <ul>
				   <li><?php echo ($ticketCode!='')?$ticketCode:__('Ticket id Shall be Updated Shortly');?></li>
				   <li><?php echo $item->getRemarks();?></li>
				   <?php if(isset($ticketCode) && $ticketCode!=''){?>
				         <li class="text-center"><a class="porto-icon-eye showticketmessage" data-tcode="<?php echo $ticketCode;?>" data-tid="<?php  echo $item->getMyticketsId()?>">View</a>
				    <?php }else {?>
						  <li class="text-center"><a class="porto-icon-eye showticketnomessage" data-tcode="<?php echo $ticketCode;?>" data-tid="<?php  echo $item->getMyticketsId()?>">View</a>
						<?php }?>
				   </li>
			   </ul>
			  <?php }?>

           <?php } else {?>
			   <ul>
				   <li><?php echo __('No Records Found'); ?></li>
			   </ul>
		   <?php }?>
				</div>

            </div>
        </div>
    </div>
    <!--End Mobile View-->
    <div class="row">
        <div class="col-md-12">
            <div class='replymessages' id="replymessages" style='display:none;'>		</div>
        </div>
    </div>
</div>

<div id="ticketmesage-modal" style="display:none;">
</div>




<script type="text/javascript">
require(['jquery','Magento_Ui/js/modal/modal','Magento_Ui/js/modal/alert','mage/mage','jquery/ui'
         ],function($, modal, alert){

	      $(".showticketmessage").click(function(){
		 var UrlMessage = '<?php echo $this->getUrl("mytickets/ajax/message"); ?>';
		 var tcode =  $(this).data("tcode");
		 var tid =  $(this).data("tid");
		 $.ajax({
                   url: UrlMessage,
                   type: "GET",
                    data: {
                          tid   : tid,
                          tcode : tcode

                      },
                    dataType: 'json',
                    async: true,
                    showLoader: true ,
                    beforeSend: function() {
                        $("#ticketmesage-modal").html('');
                    },
                    complete: function(){

                    },
                    success: function (jsonStr) {
						//console.log(jsonStr);
						var errors = jsonStr['errors'];
                         var message = jsonStr['message'];
                        if(errors == false) {
                            var ticketMessagesArr = jsonStr['ticketMessages'];
                            showMessagePopup( tid , ticketMessagesArr);
                        } else {

                             alert({
                                    title: $.mage.__('Error'),
                                    content: jsonStr.message,
                                    actions: {
                                        always: function(){}
                                    }
                              });
                        }
                    },
                    error: function (response) {
                         alert({
                                  title: $.mage.__('Error'),
                                  content: response.message,
                                  actions: {
                                        always: function(){}
                                  }
                              });
                    },
       });

	  })


          $(".showticketnomessage").click(function(){
			var UrlMessage = '<?php echo $this->getUrl("mytickets/ajax/message"); ?>';
		 var tcode =  $(this).data("tcode");
		 var tid =  $(this).data("tid");
		 $.ajax({
                   url: UrlMessage,
                   type: "GET",
                    data: {
                          tid   : tid,
                          tcode : tcode

                      },
                    dataType: 'json',
                    async: true,
                    showLoader: true ,
                    beforeSend: function() {
                        $("#ticketmesage-modal").html('');
                    },
                    complete: function(){

                    },
                    success: function (jsonStr) {
						var errors = jsonStr['errors'];
                         var message = jsonStr['message'];
                        if(errors == false) {
                            var ticketMessagesArr = jsonStr['ticketMessages'];
                            showMessagePopup( tid , ticketMessagesArr);
                        } else {

                             alert({
                                    title: $.mage.__('Error'),
                                    content: jsonStr.message,
                                    actions: {
                                        always: function(){}
                                    }
                              });
                        }
                    },
                    error: function (response) {
                         alert({
                                  title: $.mage.__('Error'),
                                  content: response.message,
                                  actions: {
                                        always: function(){}
                                  }
                              });
                    },
       });
		  });


      $(".closepopup").live('click', function(){
		  $("#replymessages").css('display','none');
	  });

        function showMessagePopup(ticketId,messagesArr){
            if(messagesArr){
                console.log(messagesArr);
                messageId =  "message"+ticketId;
                var ticketreply = '';
                ticketreply = ticketreply+"<div class='messages_section'><form action='<?php echo $this->getUrl('mytickets/ajax/addMessage');?>?id="+messagesArr['ticket_id']+"' method='post' class='ticketaddmsg'><input type='text' id='message' name='message' placeholder='Type Your Message Here..'><input type='submit' value='Submit' class='add-btn'></form>";
                ticketreply = ticketreply + '<div class="ticket_info"><ul><li>Message</li><li>Date Time</li><li>Sent By</li></ul>';
                ticketreply = ticketreply + '<ul><li>'+messagesArr['message']+'</li><li>'+messagesArr['created_at'] +'</li><li>'+messagesArr['name']+'</li></ul>';

		  ticketreply =  ticketreply+"<div class='closepopup'>×</div><div class='message_history'>";

                $.each( messagesArr['messages'], function( key, value ) {
                    var date = new Date(value.created_at);
                    ticketreply = ticketreply+"<div class='message_body'>";
                    if(value.send_by !== 'Admin'){
                        ticketreply = ticketreply+"<div class='message-name'>"+ messagesArr['name'] +": </div>";
                    }else{
                        ticketreply = ticketreply+"<div class='message-name'> Merchant: </div>";
                    }
                    ticketreply = ticketreply+"<div class='updated-at'>"+ date +"</div>";
                    ticketreply = ticketreply+"<div class='message'>"+ value.message +"</div></div>";
                });
                if(messagesArr['status'] === 1){
                    ticketreply = ticketreply+"</div></div></div>";
                }

		  $("#replymessages").html(ticketreply);
		  $("#replymessages").css('display','block');
		}

	}


	function showmessage(id){
	   var messagesmodal = document.getElementById("messages"+tid);
	   if (window.getComputedStyle(messagesmodal).display === "none") {
	   messagesmodal.style.display = "block";
	   }else{
	   messagesmodal.style.display = "none";
	   }
     }


    $(document).ready(function() {
		$('.tickets-customer-index .mobile-popup-detials .close').on('click',function(){
			$(this).parents('.modal').hide();
		});
		$('.tickets-customer-index .ticket-content li.porto-icon-eye').on('click',function(){
			var ticketCode = $(this).attr('data-ticket');
			$('.tickets-customer-index .mobile-popup-detials[data-ticketId="'+ticketId+'"]').show();
		});
	});

});
</script>

<style>
@media(max-width:767px){
	.trackbyemail-index-index .mytickets-container .replymessages .messages_section ul li:nth-child(1)::before {
		content: '<?php echo __("Message") ?>';
	}
	.trackbyemail-index-index .mytickets-container .replymessages .messages_section ul li:nth-child(2)::before {
		content: '<?php echo __("Date") ?>';
	}
	.trackbyemail-index-index .mytickets-container .replymessages .messages_section ul li:nth-child(3)::before {
		content: '<?php echo __("Time") ?>';
	}
	.trackbyemail-index-index .mytickets-container .replymessages .messages_section ul li:nth-child(4)::before {
		content: '<?php echo __("Send By") ?>';
	}
}
</style>
