<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Amp
 * @copyright   Copyright (c) 2019 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var Plumrocket\Amp\ViewModel\GlobalState $viewModel */
$viewModel = $block->getData('viewModel');
?>

<amp-state id="<?= $viewModel->getStateName() ?>">
    <script type="application/json"><?= $viewModel->getStateJson() ?></script>
</amp-state>
