<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Amp
 * @copyright   Copyright (c) 2019 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>
<?php /** @var \Plumrocket\Amp\Block\Catalog\Product\ListForm\AddToCartRenderer $block */ ?>

<?php
$setStateOption = $block->getStateModel()->createAmpJsSetter(
    $block->getStatePath(),
    $block->getProductId()
);

$getClassJs = '(' . $block->getStateName() . '.' . $block->getStatePathString() . ' == ' . $block->getProductId() . ')'
    . ' ? \'add-to-cart loading\''
    . ' : \'add-to-cart\'';
?>

<button on="tap:AMP.setState(<?= $setStateOption ?>),<?= $block->getFormId() ?>.submit"
        class="add-to-cart"
        data-vars-product-id="<?= $block->getProductId(); ?>"
        data-vars-price="<?= $block->getPrice(); ?>"
        [class]="<?= $getClassJs ?>"
>
    <?= __('Add to Cart') ?>
</button>