<?php
/**
 * @package     Plumrocket_SocialLoginFree
 * @copyright   Copyright (c) 2020 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license   End-user License Agreement
 */
?>
<?php /** @var Magento\Framework\View\Element\Template $block */ ?>
<?= $block->escapeHtml(
    __('Customer with email (%1) already exists in the database. If you are sure that it is your email address, ' .
       'please <a href="%2">click here</a> to retrieve your password and access your account.',
        $block->getData('email'),
        $block->getData('url')
    ),
    ['a']
)
?>
