<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Amp
 * @copyright   Copyright (c) 2019 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Plumrocket\Amp\Helper\Config $viewModel */
$viewModel = $block->getData('viewModel');
?>

<!-- <div class="top_contacts flex align-items-center">
    <?php if ($contactTel = $viewModel->getContactTelInHeader()) : ?>
        <a href="tel:<?= $contactTel ?>" class="top__tel">
            <i class="fas fa-phone-volume fa-1"></i><?= $contactTel ?>
        </a>
    <?php endif; ?>
    <?php if ($helpMail = $viewModel->getHelpMailInHeader()) : ?>
        <a href="mailto:<?= $helpMail ?>" class="top__help">
            <i class="far fa-question-circle fa-1"></i><?= __('Help Center') ?>
        </a>
    <?php endif; ?>
</div> -->
