<?php
/**
 * @var $block  MaxMage\InternationalTelephoneInput\Block\PhoneNumber
 */
?>
<script type="text/x-magento-init">
    {
        "input[name='telephone']": {
            "MaxMage_InternationalTelephoneInput/js/internationalTelephoneInput": <?php echo $block->phoneConfig(); ?>
        },
        "input[name='referrer_phone']": {
            "MaxMage_InternationalTelephoneInput/js/internationalTelephoneInput": <?php echo $block->phoneConfig(); ?>
        },
        "input[name='yourphonenumber']": {
            "MaxMage_InternationalTelephoneInput/js/internationalTelephoneInput": <?php echo $block->phoneConfig(); ?>
        },
        "input[name='phone']": {
            "MaxMage_InternationalTelephoneInput/js/internationalTelephoneInput": <?php echo $block->phoneConfig(); ?>
        }
    }
</script>