<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_SeoCore
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/**
 * Seo Core Validate Bing and Google
 * @var $block Bss\SeoCore\Block\Validate
 */
?>
<?php
$dataHelper = $block->getHelper();
$googleSearchConsoleValidate = $dataHelper->getGoogleVerification();
$bingValidate = $dataHelper->getBingVerification();
if ($googleSearchConsoleValidate !== '' && $googleSearchConsoleValidate !== null && $googleSearchConsoleValidate) : ?>
    <meta name="google-site-verification" content="<?php echo $block->escapeHtml($googleSearchConsoleValidate); ?>" />
<?php endif; ?>

<?php if ($bingValidate !== '' && $bingValidate !== null && $bingValidate) : ?>
    <meta name="msvalidate.01" content="<?php echo $block->escapeHtml($bingValidate); ?>" />
<?php endif; ?>
