<?php /* @var $block \Firas\DonationProduct\Block\Product\Type\Donation */ ?>

<div class="product-options-wrapper donations-option" id="product-options-wrapper">
    <div class="fieldset">
        <div class="field">
            <label class="label">
                <span><?php echo __('Choose an amount to donate'); ?></span>
            </label>
            <div class="control">
                <div class="options-list nested" id="options-4-list">
                    <?php
                        $dynamicHelper = $this->helper('\Dynamic\Customization\Helper\Data');
                        $priceCurrencyFactory = $dynamicHelper->getCurrencyManager();
                        $storeManager = $dynamicHelper->getStoreManager();
                        $currencyCodeTo = $storeManager->getStore()->getCurrentCurrency()->getCode();
                        $currencyCodeFrom = $storeManager->getStore()->getBaseCurrency()->getCode();
                        $itemAmount = 100; // product price
                    ?>
                    <?php foreach ($block->getFixedAmounts() as $fixedAmount => $viewFixedAmount) : ?>
                        <?php
                        $rate = $priceCurrencyFactory->create()->load($currencyCodeTo)->getAnyRate($currencyCodeFrom);
                        $itemAmount = $itemAmount * $rate;
                        // echo 'from:'.$currencyCodeTo.' to: '.$currencyCodeFrom.'=='.$itemAmount;
                        ?>
                        <div class="field choice admin__field">
                            <input type="radio" class="radio input-radio-fixed-donation" name="amount_fixed" value="<?php echo $fixedAmount; ?>">
                            <label class="label" for="options_4_2"><span><?php echo $viewFixedAmount; ?></span></label>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
        <div class="field">
            <label class="label">
                <span><?php echo __('Choose your own Amount %1 (minimum %2)', $block->getCurrencySymbol(), $block->getMinimalDonationAmount()); ?></span>
            </label>
            <div class="control">
                <input name="amount" id="amount" title="amount" placeholder="<?php echo $block->getCurrencySymbol(); ?>" class="<?php echo $block->getHtmlValidationClasses(); ?>" type="text" data-validate="{required:false, 'validate-number': true}" value="">
            </div>
        </div>
    </div>
</div>

<script>
    require([
        "jquery",
    ], function ($) {
        var amountInput =  $('#amount');
        $('#product_addtocart_form').on('change', '.input-radio-fixed-donation', function () {
            amountInput.removeClass('required');
            amountInput.validation().valid();
        });
        $('#product_addtocart_form').on('change', '#amount', function () {
            amountInput.validation().valid();
        });
    });
</script>
