<?php
/**
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
// @codingStandardsIgnoreFile

/** @var Js $block */

use Tigren\Ajaxsuite\Block\Js;

?>
<script type="text/x-magento-init">
{
    "*": {
        "tigren/ajaxsuite"    : <?= $block->getAjaxSuiteInitOptions(); ?>
    }
}

</script>
