<?php
/**
 * @author      LuxuryUnlimited
 * @copyright   Copyright © 2022. All rights reserved.
 */

/** @var $block \Magento\Checkout\Block\Cart\Coupon */
?>
<div id="checkout" class="coupon-list-container">
    <div id="cart-coupon-link" data-bind="scope:'coupon-link'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>

    <div id="cart-coupon-list" data-bind="scope:'coupon-list'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout(); ?>
        }
    }
</script>
